const chatsData = {
  projectsData: [
    {
      id: "project1",
      title: "Music Generation",
      chatsDataList: [
        {
          id: "1",
          title: "Lo-fi Generator",
          history: [
            {
              messageId: "1-1",
              isUser: true,
              messageTag: "",
              text: "Generate a lo-fi track with ambient textures",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "1-2",
              isUser: false,
              messageTag: "response",
              text: "Sure! Here's a lo-fi track with ambient textures...",
              foundedAudios: [],
              generationTime: 1200,
              wavesurferContainerRefs: [],
              messageTitle: "Lo-fi Ambient",
              tagsList: ["lofi", "ambient"],
            },
          ],
        },
        {
          id: "2",
          title: "Drum Patterns",
          history: [
            {
              messageId: "2-1",
              isUser: true,
              messageTag: "",
              text: "Suggest drum patterns for chill beats",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "2-2",
              isUser: false,
              messageTag: "response",
              text: "Here are some chill drum patterns you can try...",
              foundedAudios: [],
              generationTime: 900,
              wavesurferContainerRefs: [],
              messageTitle: "Chill Drums",
              tagsList: ["drums", "chill"],
            },
          ],
        },
      ],
    },
    {
      id: "project2",
      title: "Voice Processing",
      chatsDataList: [
        {
          id: "3",
          title: "Pitch Shifting",
          history: [
            {
              messageId: "3-1",
              isUser: true,
              messageTag: "",
              text: "How to shift pitch in vocals smoothly",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "3-2",
              isUser: false,
              messageTag: "response",
              text: "To shift pitch smoothly, consider using formant-preserving algorithms...",
              foundedAudios: [],
              generationTime: 1100,
              wavesurferContainerRefs: [],
              messageTitle: "Pitch Shift Guide",
              tagsList: ["pitch", "vocals"],
            },
          ],
        },
        {
          id: "4",
          title: "Noise Reduction",
          history: [
            {
              messageId: "4-1",
              isUser: true,
              messageTag: "",
              text: "Best way to reduce background noise in recordings",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "4-2",
              isUser: false,
              messageTag: "response",
              text: "Use a noise gate and spectral denoising plugins for best results.",
              foundedAudios: [],
              generationTime: 850,
              wavesurferContainerRefs: [],
              messageTitle: "Noise Tips",
              tagsList: ["noise", "vocals"],
            },
          ],
        },
      ],
    },
    {
      id: "project3",
      title: "Sound Design",
      chatsDataList: [
        {
          id: "5",
          title: "Synth Bass",
          history: [
            {
              messageId: "5-1",
              isUser: true,
              messageTag: "",
              text: "Create deep synth bass for techno",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "5-2",
              isUser: false,
              messageTag: "response",
              text: "Try using a low-passed square wave with slight saturation.",
              foundedAudios: [],
              generationTime: 1000,
              wavesurferContainerRefs: [],
              messageTitle: "Synth Bass Tips",
              tagsList: ["bass", "techno"],
            },
          ],
        },
        {
          id: "6",
          title: "SFX Layering",
          history: [
            {
              messageId: "6-1",
              isUser: true,
              messageTag: "",
              text: "Guide on layering SFX for cinematic impact",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "6-2",
              isUser: false,
              messageTag: "response",
              text: "Layer whooshes, impacts, and risers with reverb for depth.",
              foundedAudios: [],
              generationTime: 1250,
              wavesurferContainerRefs: [],
              messageTitle: "SFX Layering",
              tagsList: ["cinematic", "sfx"],
            },
          ],
        },
        {
          id: "6.2",
          title: "SFX Layering",
          history: [
            {
              messageId: "6.2-1",
              isUser: true,
              messageTag: "",
              text: "Guide on layering SFX for cinematic impact",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "6.2-2",
              isUser: false,
              messageTag: "response",
              text: "Layer whooshes, impacts, and risers with reverb for depth.",
              foundedAudios: [],
              generationTime: 1250,
              wavesurferContainerRefs: [],
              messageTitle: "SFX Layering",
              tagsList: ["cinematic", "sfx"],
            },
          ],
        },
        {
          id: "6.3",
          title: "SFX Layering",
          history: [
            {
              messageId: "6.3-1",
              isUser: true,
              messageTag: "",
              text: "Guide on layering SFX for cinematic impact",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "6.3-2",
              isUser: false,
              messageTag: "response",
              text: "Layer whooshes, impacts, and risers with reverb for depth.",
              foundedAudios: [],
              generationTime: 1250,
              wavesurferContainerRefs: [],
              messageTitle: "SFX Layering",
              tagsList: ["cinematic", "sfx"],
            },
          ],
        },
        {
          id: "6.4",
          title: "SFX Layering",
          history: [
            {
              messageId: "6.4-1",
              isUser: true,
              messageTag: "",
              text: "Guide on layering SFX for cinematic impact",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "6.4-2",
              isUser: false,
              messageTag: "response",
              text: "Layer whooshes, impacts, and risers with reverb for depth.",
              foundedAudios: [],
              generationTime: 1250,
              wavesurferContainerRefs: [],
              messageTitle: "SFX Layering",
              tagsList: ["cinematic", "sfx"],
            },
          ],
        },
        {
          id: "6.5",
          title: "SFX Layering",
          history: [
            {
              messageId: "6.5-1",
              isUser: true,
              messageTag: "",
              text: "Guide on layering SFX for cinematic impact",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "6.5-2",
              isUser: false,
              messageTag: "response",
              text: "Layer whooshes, impacts, and risers with reverb for depth.",
              foundedAudios: [],
              generationTime: 1250,
              wavesurferContainerRefs: [],
              messageTitle: "SFX Layering",
              tagsList: ["cinematic", "sfx"],
            },
          ],
        },
        {
          id: "6.6",
          title: "SFX Layering",
          history: [
            {
              messageId: "6.6-1",
              isUser: true,
              messageTag: "",
              text: "Guide on layering SFX for cinematic impact",
              foundedAudios: [],
              generationTime: 0,
              wavesurferContainerRefs: [],
              messageTitle: "",
              tagsList: [],
            },
            {
              messageId: "6.6-2",
              isUser: false,
              messageTag: "response",
              text: "Layer whooshes, impacts, and risers with reverb for depth.",
              foundedAudios: [],
              generationTime: 1250,
              wavesurferContainerRefs: [],
              messageTitle: "SFX Layering",
              tagsList: ["cinematic", "sfx"],
            },
          ],
        },
      ],
    },
  ],
  separateChatsData: [
    {
      id: "7",
      title: "General Help",
      history: [
        {
          messageId: "7-1",
          isUser: true,
          messageTag: "",
          text: "What are the best AI tools for audio editing?",
          foundedAudios: [],
          generationTime: 0,
          wavesurferContainerRefs: [],
          messageTitle: "",
          tagsList: [],
        },
        {
          messageId: "7-2",
          isUser: false,
          messageTag: "response",
          text: "Top tools include iZotope RX, Adobe Podcast AI, and Descript.",
          foundedAudios: [],
          generationTime: 1050,
          wavesurferContainerRefs: [],
          messageTitle: "AI Tools",
          tagsList: ["tools", "ai"],
        },
      ],
    },
    {
      id: "8",
      title: "Plugin Advice",
      history: [
        {
          messageId: "8-1",
          isUser: true,
          messageTag: "",
          text: "Recommend reverb plugins for vocals",
          foundedAudios: [],
          generationTime: 0,
          wavesurferContainerRefs: [],
          messageTitle: "",
          tagsList: [],
        },
        {
          messageId: "8-2",
          isUser: false,
          messageTag: "response",
          text: "Try Valhalla VintageVerb, FabFilter Pro-R, or Waves RVerb.",
          foundedAudios: [],
          generationTime: 980,
          wavesurferContainerRefs: [],
          messageTitle: "Reverb Plugins",
          tagsList: ["reverb", "vocals"],
        },
      ],
    },
    {
      id: "9",
      title: "Mixing Tips",
      history: [
        {
          messageId: "9-1",
          isUser: true,
          messageTag: "",
          text: "How to mix kick and bass together",
          foundedAudios: [],
          generationTime: 0,
          wavesurferContainerRefs: [],
          messageTitle: "",
          tagsList: [],
        },
        {
          messageId: "9-2",
          isUser: false,
          messageTag: "response",
          text: "Use sidechain compression and EQ separation for clarity.",
          foundedAudios: [],
          generationTime: 890,
          wavesurferContainerRefs: [],
          messageTitle: "Kick & Bass",
          tagsList: ["mixing", "bass"],
        },
      ],
    },
    {
      id: "10",
      title: "Mastering Chain",
      history: [
        {
          messageId: "10-1",
          isUser: true,
          messageTag: "",
          text: "What's a basic mastering chain for pop music?",
          foundedAudios: [],
          generationTime: 0,
          wavesurferContainerRefs: [],
          messageTitle: "",
          tagsList: [],
        },
        {
          messageId: "10-2",
          isUser: false,
          messageTag: "response",
          text: "EQ → Compressor → Saturator → Limiter is a typical chain.",
          foundedAudios: [],
          generationTime: 1030,
          wavesurferContainerRefs: [],
          messageTitle: "Mastering Chain",
          tagsList: ["mastering", "pop"],
        },
      ],
    },
    {
      id: "11",
      title: "Sample Rate",
      history: [
        {
          messageId: "11-1",
          isUser: true,
          messageTag: "",
          text: "Should I record at 44.1kHz or 48kHz?",
          foundedAudios: [],
          generationTime: 0,
          wavesurferContainerRefs: [],
          messageTitle: "",
          tagsList: [],
        },
        {
          messageId: "11-2",
          isUser: false,
          messageTag: "response",
          text: "Use 48kHz for video, 44.1kHz for music by default.",
          foundedAudios: [],
          generationTime: 920,
          wavesurferContainerRefs: [],
          messageTitle: "Sample Rate Advice",
          tagsList: ["sample rate", "recording"],
        },
      ],
    },
  ],
};

export default chatsData;
