import type { VueElement } from "vue";
import type { AppLayouts } from "@/utils/types/layouts.types";
import type { AccessScopes } from "@/utils/types/auth.types";

declare module "vue-router" {
  interface RouteMeta {
    layout?: AppLayouts;
    layoutComponent?: VueElement;
    accessScopes?: AccessScopes[];
  }
}

export const enum RouteNames {
  HOME = "HOME",
  ACCESS_ERROR = "ACCESS_ERROR",
  LOGIN = "LOGIN",
  LOGIN_GOOGLE_CALLBACK = "LOGIN_GOOGLE_CALLBACK",
  LOGIN_COGNITO_CALLBACK = "LOGIN_COGNITO_CALLBACK",
  SIGN_UP = "SIGN_UP",
  JG_TWITTER_OIDC_AUTHORIZATION = "OIDC_TWITTER_AUTHORIZATION",
  JG_TWITTER_OIDC_CALLBACK = "OIDC_TWITTER_CALLBACK",
  JG_METAMASK_OIDC_AUTHORIZATION = "OIDC_METAMASK_AUTHORIZATION",
  PROFILE_PAGE = "PROFILE_PAGE",
  ARTIST = "ARTIST",
  ARTISTS = "ARTISTS",
  ADMIN_PANEL = "ADMIN_PANEL",
  FORUM = "FORUM",
  FORUM_THREAD = "FORUM_THREAD",
  TEST = "TEST",
  SETTINGS_CREATOR = "SETTINGS_CREATOR",
  SETTINGS_FAN = "SETTINGS_FAN",
  SETTINGS_ARTIST = "SETTINGS_ARTIST",
  SETTINGS_ARTIST_EDIT = "SETTINGS_ARTIST_EDIT",
  NOT_FOUND = "NOT_FOUND",
  STARTPAGE = "STARTPAGE",
  MY_TEAMS = "MY_TEAMS",
  SOUND_SPLITTER = "SOUND_SPLITTER",
  AUDIO_STREAM = "AUDIO_STREAM",
  WEB3AUTH = "WEB3AUTH",
  AICHAT = "AICHAT",
  NEW_AUTHORIZATION = "NEW_AUTHORIZATION",
}
