<template>
  <div class="web3auth">
    <h1>Web3Auth Control pannel</h1>
    coreKitStatus: <span>{{ coreKitStatus }}</span>
    <div class="section">
      <h2>
        login section (in a state where the user is not logged in).
        <span :class="[isWeb3AuthLoggedIn ? 'good' : 'bad']">isLoggedIn: {{ isWeb3AuthLoggedIn }}</span>
      </h2>
      <div>Login with standard google sign-in button:<GoogleLogin :callback="loginWithGoogleButtonCallback" /></div>
      or
      <div>Login with gsi lib:<button @click="loginHandler">Login</button></div>

      <div class="section">
        <h3>
          if required share.
          <span :class="[isWeb3AuthRequiredShare ? 'good' : 'bad']">isRequiredShare: {{ isWeb3AuthRequiredShare }}</span>
        </h3>
        <h4>get factors (for info purposes)</h4>
        you can get factors and see them
        <div>
          <button @click="getDeviceFactorHandler">Get Device Factor</button>
          device factor: <span>{{ deviceFactor }}</span>
        </div>
        <br />
        <div>
          This social account is not a factor 1. It is additional factor. You will get in through SFA sdk by idToken from social provider
          <br />
          <button @click="getSocialFactor">Get Social Factor</button>
        </div>
        <br />
        <div>
          The mnemonic phrase is not stored anywhere. You need to take care of its preservation yourself!
          <br />
          <label>Input Mnemonic Recovery Factor Key:</label>
          <input v-model="mnemonicFactorPhrase" />
          <button @click="mnemonicToHexHandler">Convert Mnemonic to hex</button>
        </div>
        <br />
        <div>
          Last obtained factor in hex: <span>{{ lastObtainedFactor }}</span>
        </div>
        <br />

        <h4>send factor to web3auth</h4>
        if web3auth requires more factors from you for login purpose you can send one(or more) factor(s) to web3auth.
        <div>
          <button @click="inputDeviceFactorHandler">Send device factor</button>
        </div>
        <div>
          <button @click="inputSocialFactorHandler">Send social factor</button>
        </div>
        <div>
          <label>Input Mnemonic Recovery Factor Key:</label>
          <input v-model="mnemonicFactorPhrase" />
          <button @click="inputMnemonicFactorHandler">Send mnemonic factor</button>
        </div>
        <div>
          <label>Input any (whatever you prefer) factor in hex:</label>
          <input v-model="inputedFactorKeyHex" />
          <button @click="inputAnyFactorHandler">Send this factor</button>
        </div>

        <h4>reset account</h4>
        <button @click="criticalResetAccountHandler">[CRITICAL] Reset Account</button>
      </div>
    </div>

    <div class="section">
      <h2>
        account section.
        <span :class="[isWeb3AuthLoggedIn ? 'good' : 'bad']">isLoggedIn: {{ isWeb3AuthLoggedIn }}</span>
      </h2>
      <h4>web3auth user account information</h4>
      <div>
        <button style="cursor: pointer" @click="getUserInfoHandler">Get User Info</button>
        User Info: <span>{{ userInfo }}</span>
      </div>

      <div>
        <button style="cursor: pointer" @click="getKeyDetailsHandler">Get Key Details</button>
        Key details: <span>{{ keyDetails }}</span>
      </div>

      <h4>web3auth user account actions</h4>
      <div>
        Enables MFA. 2/2 (social login factor + hashed cloud factor) -> 2/3 (social login factor + device factor(generated by sdk) + recovery factor). Be careful. This feature removes the cloud factor. Therefore, adding new factors without calling this function will lead to the fact that only the first factor (social login + cloud hash factor) will be enough to login.
        <br />
        <button style="cursor: pointer" @click="enableMultiFactorAuthenticationHandler">Enable MFA</button>
      </div>
      <div>
        <button style="cursor: pointer" @click="addSocialFactorHandler">Add an aditional backup factor (social)</button>
      </div>
      <div>
        <button style="cursor: pointer" @click="addMnemonicFactorHandler">Add an aditional backup factor (mnemonic)</button>
        last obtained mnemonic <span>{{ lastObtainedMnemonic }}</span>
      </div>
      <div>
        <button style="cursor: pointer" @click="logout">Logout</button>
      </div>
      <div>
        <button style="cursor: pointer" @click="criticalResetAccount">[CRITICAL] Reset Account</button>
      </div>

      <h4>web3auth user wallet</h4>
      <div>
        <button style="cursor: pointer" @click="getAccounts">Get Accounts</button>
        accounts:
        <span v-for="(account, index) in web3authWallet.accounts" :key="index">{{ account }}</span>
      </div>
      <div>
        <button style="cursor: pointer" @click="getBalance">Get Balance</button>
        balance: <span>{{ web3authWallet.balance }}</span>
      </div>
      <div>
        <button style="cursor: pointer" @click="signMessage">Sign Message</button>
        signed message: <span>{{ web3authWallet.signedMessage }}</span>
      </div>
    </div>

    <div id="console" style="white-space: pre-line">
      <p style="white-space: pre-line"></p>
    </div>
  </div>
</template>

<script>
import { mapGetters, mapActions, mapState } from "vuex";

export default {
  name: "Web3Auth",
  data() {
    return {
      mnemonicFactorPhrase: "",
      inputedFactorKeyHex: "",
    };
  },
  computed: {
    ...mapState("web3auth", {
      coreKitStatus: (state) => state.coreKitStatus,
      userInfo: (state) => state.userInfo,
      keyDetails: (state) => state.keyDetails,
      deviceFactor: (state) => state.deviceFactor,
      lastObtainedFactor: (state) => state.lastObtainedFactor,
      lastObtainedMnemonic: (state) => state.lastObtainedMnemonic,
      web3authWallet: (state) => state.web3authWallet,
    }),
    ...mapGetters("web3auth", ["isWeb3AuthLoggedIn", "isWeb3AuthRequiredShare"]),
  },
  unmounted() {
    this.finish();
  },
  methods: {
    ...mapActions("web3auth", ["finish", "loginWithSocialProvider", "loginWithGoogleButtonCallback", "getDeviceFactor", "getSocialFactor", "mnemonicToHex", "inputDeviceFactor", "inputSocialFactor", "inputMnemonicFactor", "inputBackupFactorKey", "criticalResetAccount", "getUserInfo", "getKeyDetails", "enableMultiFactorAuthentication", "addAdditionalBackupFactor", "addSocialFactor", "addMnemonicFactor", "logout", "getAccounts", "getBalance", "signMessage"]),
    /* login section */
    async loginHandler() {
      await this.loginWithSocialProvider("google");
    },
    /* required share subsection */
    async getDeviceFactorHandler() {
      await this.getDeviceFactor();
    },
    mnemonicToHexHandler() {
      this.mnemonicToHex(this.mnemonicFactorPhrase);
    },
    async inputDeviceFactorHandler() {
      await this.inputDeviceFactor();
    },
    async inputSocialFactorHandler() {
      await this.inputSocialFactor();
    },
    async inputMnemonicFactorHandler() {
      await this.inputMnemonicFactor(this.mnemonicFactorPhrase);
    },
    async inputAnyFactorHandler() {
      await this.inputBackupFactorKey(this.inputedFactorKeyHex);
    },
    async criticalResetAccountHandler() {
      await this.criticalResetAccount();
    },
    /* /required share subsection */
    /* /login section */

    /* account section */
    getUserInfoHandler() {
      this.getUserInfo();
    },
    getKeyDetailsHandler() {
      this.getKeyDetails();
    },
    async enableMultiFactorAuthenticationHandler() {
      await this.enableMultiFactorAuthentication();
    },
    async addSocialFactorHandler() {
      await this.addSocialFactor();
    },
    async addMnemonicFactorHandler() {
      await this.addMnemonicFactor();
    },
    async web3authLogout() {
      await this.logout();
    },

    /* web3auth wallet */
    async getAccountsHandler() {
      await this.getAccounts();
    },
    async getBalanceHandler() {
      await this.getBalance();
    },
    async signMessageHandler() {
      await this.signMessage();
    },
    /* /web3auth wallet */
    /* /account section */
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.web3auth {
  color: var(--color-light);
}
.section {
  border: 2px solid blue;
  padding: var(--regular-padding);
}

.section:not(:last-child) {
  margin-bottom: 15px;
}

span {
  font-weight: bold;
}

.good {
  color: green;
}

.bad {
  color: red;
}

#console {
  width: 100%;
  height: 100%;
  overflow: auto;
  word-wrap: break-word;
  font-size: var(--medium-font-size);
  font-family: monospace;
  text-align: left;
}
</style>
